### ISSUE TITLE
Support for Python Pre-Commit hooks

### ISSUE THREAD

**Issue by lexi-the-cute** [rustwasm/twiggy#749]
## 💡 Feature Description

Allows testing code before commit. https://pre-commit.com

#### 💻 Example Usage

.pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: top
        args = ["-n", "20"]
    -   id: garbage
    -   id: ...
```

This'd then be used to pass or fail a commit based on if for example, the top code offenders reached above a certain size which can be configured in the config

#### 🙌 Are you interested in implementing this feature?

Add an "X" to one of the following:

* [ ] Yes
* [ ] Yes if I had a mentor to help me
* [X] No
